//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.9151
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExtWatcher.Common.Contract
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileEventArgs", Namespace="http://schemas.datacontract.org/2004/07/ExtWatcher.Common.Contract")]
    public partial class FileEventArgs : System.EventArgs, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private ExtWatcher.Common.Contract.FileAnalysisStatus AnalysisStatusField;
        
        private System.IO.WatcherChangeTypes ChangeTypeField;
        
        private System.DateTime DateField;
        
        private string FileNameField;
        
        private string FolderField;
        
        private System.Guid IdField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ExtWatcher.Common.Contract.FileAnalysisStatus AnalysisStatus
        {
            get
            {
                return this.AnalysisStatusField;
            }
            set
            {
                this.AnalysisStatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.IO.WatcherChangeTypes ChangeType
        {
            get
            {
                return this.ChangeTypeField;
            }
            set
            {
                this.ChangeTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FileName
        {
            get
            {
                return this.FileNameField;
            }
            set
            {
                this.FileNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Folder
        {
            get
            {
                return this.FolderField;
            }
            set
            {
                this.FolderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileAnalysisStatus", Namespace="http://schemas.datacontract.org/2004/07/ExtWatcher.Common.Contract")]
    public enum FileAnalysisStatus : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Unknown = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Malicious = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Benign = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Aborted = 3,
    }
}
namespace System.IO
{
    using System;
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.FlagsAttribute()]
    [System.Runtime.Serialization.DataContractAttribute(Name="WatcherChangeTypes", Namespace="http://schemas.datacontract.org/2004/07/System.IO")]
    public enum WatcherChangeTypes : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Created = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Deleted = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Changed = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Renamed = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        All = 15,
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="INotify", CallbackContract=typeof(INotifyCallback), SessionMode=System.ServiceModel.SessionMode.Required)]
public interface INotify
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotify/Register", ReplyAction="http://tempuri.org/INotify/RegisterResponse")]
    void Register(System.Guid instanceId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotify/UnRegister", ReplyAction="http://tempuri.org/INotify/UnRegisterResponse")]
    void UnRegister(System.Guid instanceId);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotify/Start", ReplyAction="http://tempuri.org/INotify/StartResponse")]
    void Start(string folderToMonitor);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/INotify/Stop", ReplyAction="http://tempuri.org/INotify/StopResponse")]
    void Stop(string folderToMonitor);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface INotifyCallback
{
    
    [System.ServiceModel.OperationContractAttribute(Action= "http://tempuri.org/INotify/OnSentNotification", ReplyAction= "http://tempuri.org/INotify/OnSentNotificationResponse")]
    void OnSentNotification(ExtWatcher.Common.Contract.FileEventArgs e);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface INotifyChannel : INotify, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class NotifyClient : System.ServiceModel.DuplexClientBase<INotify>, INotify
{
    
    public NotifyClient(System.ServiceModel.InstanceContext callbackInstance) : 
            base(callbackInstance)
    {
    }
    
    public NotifyClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
            base(callbackInstance, endpointConfigurationName)
    {
    }
    
    public NotifyClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
            base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }
    
    public NotifyClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(callbackInstance, endpointConfigurationName, remoteAddress)
    {
    }
    
    public NotifyClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(callbackInstance, binding, remoteAddress)
    {
    }
    
    public void Register(System.Guid instanceId)
    {
        base.Channel.Register(instanceId);
    }
    
    public void UnRegister(System.Guid instanceId)
    {
        base.Channel.UnRegister(instanceId);
    }
    
    public void Start(string folderToMonitor)
    {
        base.Channel.Start(folderToMonitor);
    }
    
    public void Stop(string folderToMonitor)
    {
        base.Channel.Stop(folderToMonitor);
    }
}
